name: Build and Push Docker Image

on:
  push:
    branches: [main] #declancher ce workflow sur chaque push vers la branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
       # Étape 1 : Vérifier le code depuis le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #utilise les secrets docker
          password: ${{ secrets.DOCKER_PASSWORD }}
       # Étape 3 : Construire l'image Docker
      - name: Build the Docker image
        run: docker build -t ilhamaka/hello_docker:latest .
       #Etape 4 : Pousser l'image Docker sur Docker Hub 
      - name:  Push the image to Docker Hub
        run: docker push ilhamaka/hello_docker:latest
